name: test-verilated-peripherals

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      renode_gitrev:
        description: 'Renode git revision'
        required: false
        default: ''
      renode_gitrepo:
        description: 'Renode git repository'
        required: false
        default: ''

env:
  VERILATOR_VERSION: "4.200"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: "x86_64", os: "ubuntu-20.04"   }
          - { arch: "x86_64", os: "macos-13"       }
          - { arch: "x86_64", os: "windows-latest" }
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ccache
          key: ${{ runner.os }}-${{ matrix.config.arch }}

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          update: true
          install: >-
            git
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            patch

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.5' # newer version breaks pip on Windows

      - name: Build Renode
        uses: antmicro/renode-test-action@78e626d8325fdf63e02c2a4e791ed6125c8c8143
        with:
          renode-repository: ${{ inputs.renode_gitrepo || 'https://github.com/renode/renode' }}
          renode-revision: ${{ inputs.renode_gitrev || 'master' }}

      - name: Build peripherals for ${{ runner.os }}
        run: |
          set -ex
          RUNNER_OS=${{ runner.os }}
          MAKE_BIN="make"
          BUILD_ARCH=${{ matrix.config.arch }}
          if [ "$RUNNER_OS" = "Windows" ]; then
            if [ -z "$REEXECED_UNDER_MSYS" ]; then
              REEXECED_UNDER_MSYS=1 exec cmd //c "$RUNNER_TEMP/setup-msys2/msys2 $0"
            fi
            MAKE_BIN="mingw32-make.exe"
            # setup-python doesn't set path when using MSYS2 on Windows
            export PATH="$PATH:/c/hostedtoolcache/windows/Python/3.11.5/x64"
            export PATH="$PATH:/c/hostedtoolcache/windows/Python/3.11.5/x64/Scripts"
          fi
          git submodule update --init --recursive
          source .github/scripts/build-verilator.sh
          source .github/scripts/build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: renode-verilator-integration-${{ runner.os }}-${{ matrix.config.arch }}-${{ github.run_id }}
          path: artifacts/samples/*

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: "x86_64", os: "ubuntu-20.04"   }
          - { arch: "x86_64", os: "macos-13"       }
          - { arch: "x86_64", os: "windows-latest" }
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: renode-verilator-integration-${{ runner.os }}-${{ matrix.config.arch }}-${{ github.run_id }}
          path: artifacts/samples
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.5' # newer version breaks pip on Windows

      - name: Build Renode
        uses: antmicro/renode-test-action@78e626d8325fdf63e02c2a4e791ed6125c8c8143
        with:
          renode-repository: ${{ inputs.renode_gitrepo || 'https://github.com/renode/renode' }}
          renode-revision: ${{ inputs.renode_gitrev || 'master' }}

      - name: Test peripherals for ${{ runner.os }}
        run: .github/scripts/test.sh

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-output-${{ runner.os }}-${{ matrix.config.arch }}-${{ github.run_id }}
          path: results
