name: test-verilated-peripherals

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      renode_gitrev:
        description: 'Renode git revision'
        required: false
        default: ''

env:
  RENODE_GITREV: "${{ github.event.inputs.renode_gitrev }}"
  VERILATOR_VERSION: "4.200"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: "x86_64", os: "ubuntu-20.04"   }
          - { arch: "x86_64", os: "macos-13"       }
          - { arch: "x86_64", os: "windows-latest" }
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ccache
          key: ${{ runner.os }}-${{ matrix.config.arch }}

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          update: true
          install: >-
            git
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            patch

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.5' # newer version breaks pip on Windows

      - name: Download and build Renode
        run: |
          set -ex
          RUNNER_OS=${{ runner.os }}
          source .github/scripts/build-renode.sh
          mkdir -p artifacts
          tar -c --dereference -zf artifacts/renode.tar.gz renode/

      - name: Build peripherals for Windows
        if: ${{ runner.os == 'Windows' }}
        shell: msys2 {0}
        run: |
          set -ex
          RUNNER_OS="Windows"
          MAKE_BIN="mingw32-make.exe"
          BUILD_ARCH=${{ matrix.config.arch }}
          git submodule update --init --recursive

          # setup-python doesn't set path when using MSYS2 on Windows
          export PATH="$PATH:/c/hostedtoolcache/windows/Python/3.11.5/x64"
          export PATH="$PATH:/c/hostedtoolcache/windows/Python/3.11.5/x64/Scripts"

          source .github/scripts/build-verilator.sh
          source .github/scripts/build.sh

      - name: Build peripherals for ${{ runner.os }}
        if: ${{ runner.os != 'Windows' }}
        run: |
          set -ex
          RUNNER_OS=${{ runner.os }}
          MAKE_BIN="make"
          BUILD_ARCH=${{ matrix.config.arch }}
          git submodule update --init --recursive
          source .github/scripts/build-verilator.sh
          source .github/scripts/build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: renode-verilator-integration-${{ runner.os }}-${{ matrix.config.arch }}-${{ github.run_id }}
          path: artifacts/*

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: "x86_64", os: "ubuntu-20.04"   }
          - { arch: "x86_64", os: "macos-13"       }
          - { arch: "x86_64", os: "windows-latest" }
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: renode-verilator-integration-${{ runner.os }}-${{ matrix.config.arch }}-${{ github.run_id }}
          path: artifacts
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.5' # newer version breaks pip on Windows

      - name: Test peripherals for ${{ runner.os }}
        run: |
          set -ex
          tar -xf artifacts/renode.tar.gz
          source .github/scripts/test.sh

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-output-${{ runner.os }}-${{ matrix.config.arch }}-${{ github.run_id }}
          path: renode/output/tests/*
